/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './*.html'],
  darkMode: 'class',
  // Classes toggled at runtime by inline scripts (kept even if not statically obvious).
  safelist: [
    'flex', 'hidden',
    'opacity-0', 'opacity-100',
    'translate-y-0', 'translate-y-10',
    'transition-all', 'duration-1000',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#e2e2e2',
        'primary-fixed-dim': '#ffb59a',
        'outline-variant': '#e4beb1',
        'on-surface-variant': '#5b4137',
        'surface-container-highest': '#e2e2e2',
        'on-primary-fixed': '#370e00',
        'error': '#ba1a1a',
        'surface-tint': '#a73a00',
        'tertiary': '#5e5e5e',
        'on-primary-fixed-variant': '#802a00',
        'secondary-fixed-dim': '#ffb68f',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#6d3919',
        'on-background': '#1a1c1c',
        'primary': '#a73a00',
        'on-tertiary-fixed': '#1b1b1b',
        'secondary-container': '#feb289',
        'on-tertiary-fixed-variant': '#474747',
        'secondary-fixed': '#ffdbca',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#dadada',
        'tertiary-fixed-dim': '#c6c6c6',
        'surface-bright': '#f9f9f9',
        'on-error': '#ffffff',
        'inverse-primary': '#ffb59a',
        'on-primary': '#ffffff',
        'surface-container-low': '#f3f3f4',
        'inverse-on-surface': '#f0f1f1',
        'on-secondary-container': '#794222',
        'on-secondary-fixed': '#331200',
        'surface': '#f9f9f9',
        'inverse-surface': '#2f3131',
        'on-primary-container': '#521800',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'outline': '#8f7065',
        'primary-container': '#ff5c00',
        'surface-container-high': '#e8e8e8',
        'tertiary-container': '#929292',
        'background': '#f9f9f9',
        'primary-fixed': '#ffdbce',
        'error-container': '#ffdad6',
        'surface-variant': '#e2e2e2',
        'on-surface': '#1a1c1c',
        'secondary': '#89502e',
        'on-tertiary-container': '#2b2b2b',
        'surface-container': '#eeeeee',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'container-padding-desktop': '40px',
        'section-gap': '48px',
        gutter: '16px',
        'container-padding-mobile': '20px',
        'gutter-desktop': '32px',
        base: '8px',
        'max-width': '1280px',
        'margin-desktop': '64px',
        'margin-mobile': '24px',
        'gutter-mobile': '16px',
        'section-padding-desktop': '120px',
        'section-padding-mobile': '48px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'label-bold': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'stats-number': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'stats-number': ['36px', { lineHeight: '1.0', fontWeight: '800' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
